services:
  - type: web
    name: dijitalmenu
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: AppUrl
        sync: false
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Seed__AdminUsername
        sync: false
      - key: Seed__AdminPassword
        sync: false
