import { ArrowRight, Check, ChevronRight, QrCode, Sparkles, Store, Utensils, Zap } from 'lucide-react'

const dishes = [
  { name: 'Köz Patlıcan', detail: 'Tahin, nar ekşisi, çıtır nohut', price: '₺240', color: 'bg-[#d9b285]' },
  { name: 'Levrek Izgara', detail: 'Mevsim yeşillikleri & limon', price: '₺480', color: 'bg-[#a8b7a5]' },
  { name: 'Antep Katmeri', detail: 'Kaymak, Antep fıstığı', price: '₺210', color: 'bg-[#d6a56d]' },
]

function PhonePreview() {
  return <div className="relative mx-auto w-[290px] rotate-2 rounded-[38px] border-[8px] border-[#25221e] bg-[#f9f4eb] p-3 shadow-2xl shadow-[#183f32]/20 sm:w-[320px]">
    <div className="mx-auto mb-3 h-1 w-16 rounded-full bg-[#25221e]" />
    <div className="rounded-[27px] bg-[#eee7da] p-5">
      <div className="mb-6 flex items-center justify-between"><div><span className="text-[9px] uppercase tracking-[.22em] text-[#81786c]">Günün menüsü</span><h3 className="serif mt-1 text-2xl">Köşe</h3></div><div className="grid size-9 place-items-center rounded-full bg-[#215b48] text-white"><QrCode /></div></div>
      <div className="mb-5 rounded-2xl bg-[#215b48] p-4 text-white"><p className="text-[10px] uppercase tracking-[.18em] text-white/60">Şefin seçimi</p><p className="serif mt-1 text-xl">Levrek Izgara</p><div className="mt-4 flex items-center justify-between text-xs"><span>Mevsimlik</span><span>₺480</span></div></div>
      <div className="flex gap-2 overflow-hidden pb-5 text-[10px] whitespace-nowrap"><span className="rounded-full bg-[#e1a248] px-3 py-2 text-white">Tümü</span><span className="rounded-full bg-white px-3 py-2">Başlangıç</span><span className="rounded-full bg-white px-3 py-2">Ana yemek</span></div>
      <div className="flex flex-col gap-3">{dishes.slice(0,2).map((dish)=><div className="flex items-center gap-3" key={dish.name}><div className={`size-12 shrink-0 rounded-xl ${dish.color}`} /><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{dish.name}</p><p className="truncate text-[10px] text-[#81786c]">{dish.detail}</p></div><span className="text-xs font-semibold">{dish.price}</span></div>)}</div>
    </div>
  </div>
}

export default function Home() {
  return <main className="grain min-h-screen overflow-hidden">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><a href="#top" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid size-9 place-items-center rounded-xl bg-[#215b48] text-white"><QrCode /></span><span>Dijital<span className="text-[#c78224]">Menü</span></span></a><div className="hidden items-center gap-8 text-sm text-[#716d64] md:flex"><a href="#neden">Neden Dijital Menü?</a><a href="#ozellikler">Özellikler</a><a href="#fiyat">Fiyatlandırma</a></div><a href="#basla" className="rounded-full border border-[#cfc5b5] px-5 py-2.5 text-sm font-semibold transition hover:bg-[#215b48] hover:text-white">Giriş yap</a></nav>
    <section id="top" className="hero-glow mx-auto grid max-w-7xl items-center gap-16 px-6 pb-24 pt-14 lg:grid-cols-[1.05fr_.95fr] lg:px-10 lg:pb-36 lg:pt-20"><div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#d8cdbd] bg-[#fbf8f1]/70 px-4 py-2 text-xs font-semibold text-[#716d64]"><Sparkles className="size-3.5 text-[#c78224]" /> Restoranlar için yeni nesil deneyim</div><h1 className="serif max-w-2xl text-6xl leading-[.98] tracking-[-.045em] sm:text-7xl lg:text-[88px]">Menünüz,<br /><span className="text-[#215b48]">masanızın</span><br />en iyi hali.</h1><p className="mt-8 max-w-lg text-lg leading-8 text-[#716d64]">Karmaşık olmayan, zarif ve hızlı bir dijital menü. Misafirlerinizin deneyimini yükseltin, işletmenizi kolayca yönetin.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><a href="#basla" className="inline-flex items-center justify-center gap-3 rounded-full bg-[#215b48] px-7 py-4 text-sm font-semibold text-white shadow-lg shadow-[#215b48]/20 transition hover:-translate-y-1">Ücretsiz başlayın <ArrowRight className="size-4" /></a><a href="#demo" className="inline-flex items-center justify-center gap-2 rounded-full px-7 py-4 text-sm font-semibold text-[#716d64] transition hover:bg-white">Nasıl çalışır? <ChevronRight className="size-4" /></a></div><div className="mt-10 flex items-center gap-5 text-xs text-[#81786c]"><div className="flex -space-x-2"><span className="size-8 rounded-full border-2 border-[#f6f1e8] bg-[#cba37b]" /><span className="size-8 rounded-full border-2 border-[#f6f1e8] bg-[#879e87]" /><span className="size-8 rounded-full border-2 border-[#f6f1e8] bg-[#a77b65]" /></div><span><strong className="text-[#171614]">1.200+</strong> restoran bize güveniyor</span></div></div><div className="relative" id="demo"><div className="absolute -left-3 top-16 hidden rounded-2xl border border-white/70 bg-white/80 p-4 shadow-xl backdrop-blur md:block"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#e8f0e9] text-[#215b48]"><Zap className="size-4" /></span><div><p className="text-xs font-semibold">Anında güncelle</p><p className="text-[10px] text-[#81786c]">Menünüz her zaman güncel</p></div></div></div><PhonePreview /><div className="absolute -bottom-4 -right-2 rounded-2xl border border-white/70 bg-white/80 p-4 shadow-xl backdrop-blur"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#f8ead3] text-[#c78224]"><QrCode className="size-4" /></span><div><p className="text-xs font-semibold">QR hazır</p><p className="text-[10px] text-[#81786c]">Masanıza yerleştirin</p></div></div></div></div></section>
    <section id="neden" className="bg-[#215b48] px-6 py-20 text-white lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="mb-4 text-xs font-semibold uppercase tracking-[.25em] text-[#e1a248]">Neden Dijital Menü?</p><h2 className="serif text-5xl leading-tight sm:text-6xl">İyi yemek,<br />iyi bir sunumu hak eder.</h2></div><div id="ozellikler" className="mt-16 grid gap-5 md:grid-cols-3"><div className="rounded-3xl border border-white/15 bg-white/10 p-7"><Store className="mb-12 text-[#e1a248]" /><h3 className="serif text-2xl">Markanıza özel</h3><p className="mt-3 text-sm leading-6 text-white/65">Renklerinizi, hikayenizi ve menünüzü tek bir zarif deneyimde buluşturun.</p></div><div className="rounded-3xl border border-white/15 bg-white/10 p-7"><Zap className="mb-12 text-[#e1a248]" /><h3 className="serif text-2xl">Saniyeler içinde</h3><p className="mt-3 text-sm leading-6 text-white/65">Fiyat veya ürün değişikliklerini anında yayınlayın. Baskı maliyetlerine veda edin.</p></div><div className="rounded-3xl border border-white/15 bg-white/10 p-7"><Utensils className="mb-12 text-[#e1a248]" /><h3 className="serif text-2xl">Daha iyi deneyim</h3><p className="mt-3 text-sm leading-6 text-white/65">Misafirlerinizin telefonunda hızlı, erişilebilir ve iştah açıcı bir menü.</p></div></div></div></section>
    <section id="basla" className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 px-6 py-20 lg:flex-row lg:items-center lg:px-10 lg:py-28"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.25em] text-[#c78224]">Hazır mısınız?</p><h2 className="serif max-w-xl text-5xl leading-tight">Restoranınız için daha iyi bir başlangıç.</h2></div><a href="/restaurant/auth/register" className="inline-flex items-center gap-3 rounded-full bg-[#e1a248] px-7 py-4 text-sm font-semibold text-white shadow-lg shadow-[#e1a248]/20 transition hover:-translate-y-1">Ücretsiz hesabınızı açın <ArrowRight className="size-4" /></a></section>
    <footer className="border-t border-[#ded5c8] px-6 py-7 text-xs text-[#81786c] lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 sm:flex-row"><span>© 2026 Dijital Menü</span><span>Restoranınızın dijital masası</span></div></footer>
  </main>
}
